language: node_js
node_js:
  - lts/*
jobs:
  include:
    - stage: Backend tests
      before_script:
        - "sh -c 'cd ./backend && yarn install'"
      script: "sh -c 'cd ./backend && yarn test'"
  include:
    - stage: Frontend tests
      before_script:
        - "sh -c 'cd ./frontend && yarn install'"
      script: "sh -c 'cd ./frontend && yarn test'"

