language: node_js
node_js:
- lts/*
deploy:
  api_key:
    secure: VKt0/qyFbQi+UU0V8MSm9NehTE7in5aPO4r4MvYflKzzgGF4RFtvMoECd1b4CBzbjokatz/r/JnCBGZ9Pf9svPOwm02bD4bKsecUwJR1Nsp1w8388ug4+nfGHGbm7E2ZNKX0dykldJsfdFQymcb09R4I9h4Ok0TN0UWPAZJdtBIV69s4+gTdQwcoatdxjSih8gz+BAqG8z4UovfxvkuaGZOxdjpQudIrK9dPOs+J5htYTFcj/prTzFetCdxOkUSJTjr6uzI6YOG1PKAie1j2PmdrYtNfakG/Z3egGan5ZqievUaOf2QO8NHwlegXMB9FAAHKsqfNqwg5mnnz3oV9qFKjh1FTxHUia7jv7zr+AiWVRnDIUkVsdobQMDFhSeGpfEESCjLmIZfJe0mnuKcBItWLCOjsyyI4cb5fsh1dhYQ5N0+HyPmOGVMocD15peZSkztX1ClYui/TvgZf3z4khPUTT7TOt0Ys4AoaCjii+IpyqLHQjKQNbAQUslp2wKJtD4YsYyI5bGPdCDDAKXooNHwJ/1ZKjDZmwAKrQWLynn5Y21e7sfew6SFSxEOPbpInZZx5AeWrWxacpwfrlF43W3HWfQscgnUzSqg0Bf78+XF3ONR0h4bHursnpa2dTPn1YtK51vE071Ymi/1HSGtVz+I71w18RKvXh3+qlteZIAg=
